<?php

namespace Geccomedia\Weclapp\Models;

use Geccomedia\Weclapp\Model;

/**
 * @property string|null $articleNumber
 * @property string|null $name
 * @property string|null $description
 * @property string|null $shortDescription1
 * @property string|null $shortDescription2
 * @property string|null $articleType
 * @property string|null $unitId
 * @property string|null $unitName
 * @property string|null $taxId
 * @property string|null $taxName
 * @property string|null $manufacturerId
 * @property string|null $manufacturerName
 * @property string|null $manufacturerPartNumber
 * @property string|null $ean
 * @property string|null $customsTariffNumberId
 * @property string|null $countryOfOriginCode
 * @property string|null $warehouseId
 * @property string|null $warehouseName
 * @property float|null $sellPrice
 * @property float|null $purchasePrice
 * @property float|null $netWeight
 * @property float|null $grossWeight
 * @property bool|null $active
 * @property bool|null $serialNumberRequired
 * @property bool|null $batchNumberRequired
 * @property array|null $articleCategories
 * @property array|null $articlePrices
 * @property array|null $articleSupplySources
 * @property string|null $accountId
 * @property string|null $accountingCodeId
 * @property bool|null $applyCashDiscount
 * @property array|null $articleAlternativeQuantities
 * @property array|null $articleCalculationPrices
 * @property string|null $articleCategoryId
 * @property float|null $articleGrossWeight
 * @property float|null $articleHeight
 * @property array|null $articleImages
 * @property float|null $articleLength
 * @property float|null $articleNetWeight
 * @property float|null $articleWidth
 * @property array|null $availableForSalesChannels
 * @property bool|null $availableInSale
 * @property int|null $averageDeliveryTime
 * @property string|null $barcode
 * @property bool|null $billOfMaterialPartDeliveryPossible
 * @property string|null $catalogCode
 * @property float|null $commissionRate
 * @property string|null $contractBillingCycle
 * @property string|null $contractBillingMode
 * @property array|null $customAttributes
 * @property array|null $customerArticleNumbers
 * @property string|null $customsDescription
 * @property string|null $defaultLoadingEquipmentIdentifierId
 * @property string|null $defaultPriceCalculationType
 * @property array|null $defaultStoragePlaces
 * @property bool|null $defineIndividualTaskTemplates
 * @property string|null $expenseAccountId
 * @property int|null $expirationDays
 * @property float|null $fixedPurchaseQuantity
 * @property string|null $internalNote
 * @property string|null $invoicingType
 * @property string|null $launchDate
 * @property string|null $loadingEquipmentArticleId
 * @property string|null $longText
 * @property int|null $lowLevelCode
 * @property string|null $marginCalculationPriceType
 * @property string|null $matchCode
 * @property float|null $minimumPurchaseQuantity
 * @property float|null $minimumStockQuantity
 * @property float|null $packagingQuantity
 * @property string|null $packagingUnitBaseArticleId
 * @property string|null $packagingUnitParentArticleId
 * @property float|null $plannedWorkingTimePerUnit
 * @property string|null $primarySupplySourceId
 * @property int|null $procurementLeadDays
 * @property string|null $producerType
 * @property bool|null $productionArticle
 * @property array|null $productionBillOfMaterialItems
 * @property string|null $productionConfigurationRule
 * @property string|null $purchaseCostCenterId
 * @property array|null $quantityConversions
 * @property string|null $ratingId
 * @property string|null $recordItemGroupName
 * @property int|null $safetyStockDays
 * @property array|null $salesBillOfMaterialItems
 * @property string|null $salesCostCenterId
 * @property string|null $sellByDate
 * @property string|null $sellFromDate
 * @property string|null $serviceArticleForServiceQuotaBookingId
 * @property float|null $serviceQuotaQuantity
 * @property bool|null $showOnDeliveryNote
 * @property string|null $statusId
 * @property array|null $supplySources
 * @property string|null $supportUntilDate
 * @property string|null $systemCode
 * @property array|null $tags
 * @property float|null $targetStockQuantity
 * @property string|null $taxRateType
 * @property bool|null $useAvailableForSalesChannels
 * @property bool|null $useSalesBillOfMaterialItemPrices
 * @property bool|null $useSalesBillOfMaterialItemPricesForPurchase
 * @property bool|null $useSalesBillOfMaterialSubitemCosts
 */
class Article extends Model {}
